#!/bin/bash

# This script uses qrsh to perform a cp command on each
# node that a user has allocated.

# This is useful for populating $TMPDIR on multiple nodes.

# Dr Owain Kenway, UCL

# For licensing terms, see LICENSE.txt

if [[ ! -d "$TMPDIR" ]]; then
  echo "Error: no TMPDIR set: gecp cannot find \$TMPDIR/machines"
  exit 2
fi

if [[ ! -r "$TMPDIR/machines" ]]; then
  echo "Error: no machinefile: gecp cannot find $TMPDIR/machines"
  exit 3
fi

sort -u "$TMPDIR/machines" > "$TMPDIR/uniqmachines"

echo "Using nodes:" >&2
cat "$TMPDIR/uniqmachines" >&2

declare -a pids
for node in $(cat "$TMPDIR/uniqmachines"); do
  # TODO Think of a way to fix this --v
  # WARN: This will break if any of the command line arguments contain spaces
  qrsh -inherit "$node" "cd \"$(pwd)\"; /bin/cp $*" &
  pids+=("$!")
done

wait "${pids[@]}"
