#!/bin/bash

# Parallel launcher for the various PEs on Legion.
# Dr Owain Kenway, UCL

# For licensing terms, see LICENSE.txt

set -e

# See if GERUN_PATH is set, otherwise guess it out from $0.
export GERUN_PATH="${GERUN_PATH:-$(dirname $(readlink -f $(which $0)))}"

# Load function definitions.
source $GERUN_PATH/gerunlib.sh

export OMP_NUM_THREADS="${OMP_NUM_THREADS:-1}"

GE_OMPI_OPTS=""

if [[ "$OMP_NUM_THREADS" != "1" ]]; then
  stderrmsg "ERROR: You are attempting to launch a mixed mode code on a version of" 
  stderrmsg "OpenMPI built with GE integration.  This will not work correctly."
  stderrmsg "Exiting."
  $GE_OMPI_OPTS="--bynode"
else
  mpirun ${GE_OMPI_OPTS} "$@"
fi
