#!/bin/bash

# Parallel launcher for the various PEs on Legion.
# Dr Owain Kenway, UCL

# For licensing terms, see LICENSE.txt

set -e

# See if GERUN_PATH is set, otherwise guess it out from $0.
export GERUN_PATH="${GERUN_PATH:-$(dirname $(readlink -f $(which $0)))}"

# Load function definitions.
source $GERUN_PATH/gerunlib.sh

export OMP_NUM_THREADS="${OMP_NUM_THREADS:-1}"

if [[ "$OMP_NUM_THREADS" != "1" ]]; then
  mpirun --bynode -np "$GERUN_PROCS" "$@"
else
  mpirun  "$@"
fi
