#!/bin/bash

# Parallel launcher for the various PEs on Legion.
# Dr Owain Kenway, UCL

# For licensing terms, see LICENSE.txt

mpirun \
  -machinefile "$TMPDIR/machines" \
  -np "$GERUN_PROCS" \
  "$@"
