#!/bin/bash

# Parallel launcher for the various PEs on Legion.
# Dr Owain Kenway, UCL

# For licensing terms, see LICENSE.txt

# See if GERUN_PATH is set, otherwise guess it out from $0.
export GERUN_PATH="${GERUN_PATH:-$(dirname $(readlink -f $(which $0)))}"

# Load function definitions.
source $GERUN_PATH/gerunlib.sh

# Fail and print useful error if no MPI loaded.
stderrmsg "Error: You don't appear to have an MPI implementation loaded.  Exiting."

if declare -f module >/dev/null; then
  stderrmsg ""
  module list -t
fi
